apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: master-fileintegrity
  namespace: openshift-file-integrity
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  nodeSelector:
      node-role.kubernetes.io/master: ""
  config:
    gracePeriod: 900
    maxBackups: 5
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists