apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/file-integrity-operator.openshift-file-integrity: ""
  name: file-integrity-operator
  namespace: openshift-file-integrity
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: release-0.1
  installPlanApproval: Manual
  name: file-integrity-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace