apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: worker-fileintegrity
  namespace: openshift-file-integrity
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  nodeSelector:
      node-role.kubernetes.io/worker: ""
  config:
    gracePeriod: 900
    maxBackups: 5