apiVersion: v1
kind: ResourceQuota
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: argo-git
  name: dev-resourcequota
  namespace: dev
spec:
  hard:
    limits.cpu: "3000m"
    limits.memory: "45Gi"
    requests.cpu: "3000m"
    requests.memory: "45Gi"
    persistentvolumeclaims: "3"
    trident-ontap-mw.storageclass.storage.k8s.io/requests.storage: "0Gi"
