apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: argo-git
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  name: edit
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: customer-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: dse_editors